/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";

type Project = { id: string; title: string; status: string; photo_ids: string[]; captions: string[]; bgm: string; current_render_id?: string; work_id?: string };
type Render = { id: string; status: string; progress: number; work_id?: string; project_work_id?: string; error_code?: string };

export function VideoProjectClient({ id }: { id: string }) {
  const [project, setProject] = useState<Project | null>(null); const [render, setRender] = useState<Render | null>(null); const [caption, setCaption] = useState(""); const [message, setMessage] = useState("");
  async function load() { const next = await apiFetch<Project>(`/api/video-projects/${id}`); setProject(next); if (next.current_render_id) setRender(await apiFetch<Render>(`/api/video-renders/${next.current_render_id}`)); }
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!render || !["queued", "processing"].includes(render.status)) return; const timer = window.setInterval(() => load().catch(() => undefined), 2500); return () => window.clearInterval(timer); }, [render?.status]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save() { if (!project) return; try { setProject(await apiFetch<Project>(`/api/video-projects/${id}`, { method: "PATCH", body: JSON.stringify({ captions: caption ? [caption] : project.captions }) })); setMessage("草稿已保存"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function renderNow() { try { setRender(await apiFetch<Render>(`/api/video-projects/${id}/render`, { method: "POST" })); setMessage("已进入渲染队列"); } catch (error) { setMessage(error instanceof Error ? error.message : "提交失败"); } }
  async function order() { if (!render?.work_id) return; try { const created = await apiFetch<{ id: string }>("/api/orders", { method: "POST", body: JSON.stringify({ workId: render.work_id, sku: "pl-19-single" }) }); await apiFetch(`/api/orders/${created.id}/pay`, { method: "POST" }); setMessage("高清权益已解锁"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "支付失败"); } }
  if (!project) return <div className="empty-state">正在读取项目…</div>;
  return <><section className="panel"><div className="section-heading"><div><span className="eyebrow">{project.status}</span><h2>{project.title}</h2></div><span>{render ? `${render.progress}%` : "未提交"}</span></div><div className="progress-track"><span style={{ width: `${render?.progress || 0}%` }} /></div><div className="field"><label htmlFor="project-caption">逐段字幕</label><textarea id="project-caption" value={caption || project.captions?.[0] || ""} onChange={(event) => setCaption(event.target.value)} placeholder="写一句想留在视频里的话" /></div><div className="button-row"><button className="secondary-button" onClick={save} type="button">保存草稿</button><button className="primary-button" onClick={renderNow} type="button" disabled={Boolean(render && ["queued", "processing"].includes(render.status))}>提交渲染</button>{render?.status === "failed" ? <button className="secondary-button" onClick={() => apiFetch<Render>(`/api/video-renders/${render.id}/retry`, { method: "POST" }).then(setRender)} type="button">重试</button> : null}{render && ["queued", "processing", "preview_ready"].includes(render.status) ? <button className="secondary-button" onClick={() => apiFetch<Render>(`/api/video-renders/${render.id}/cancel`, { method: "POST" }).then(setRender)} type="button">取消</button> : null}</div></section>{render?.status === "preview_ready" || render?.status === "ready" ? <section className="panel" style={{ marginTop: 20 }}><span className="eyebrow">PREVIEW</span><video controls playsInline src={`/api/video-renders/${render.id}/download`} style={{ width: "100%", borderRadius: 18, marginTop: 12 }} /><div className="button-row" style={{ marginTop: 16 }}><a className="secondary-button" href={`/api/video-renders/${render.id}/download`}>下载预览</a>{render.status === "preview_ready" ? <button className="primary-button" onClick={order} type="button">支付 ¥19.90 解锁高清</button> : <a className="primary-button" href={`/api/works/${render.work_id}/download?format=video`}>下载高清 MP4</a>}</div></section> : null}{message ? <div className="error-banner" role="status">{message}</div> : null}</>;
}
