/**
 * 手账相册（2026-09 重做，原「暖调胶片」）。
 *
 * 空间隐喻：书桌上摊开的相册。纸张拼贴：米纸底、相纸白卡、近直角、下沿纸叠硬影、
 * 拍立得白边、胶带标题、衬线标题。照片本身保留原色，不加滤镜。
 * `degrade` 描述 backdrop-filter 不生效时的替代取值，由 ThemeManager 在初始化探测后一次性应用。
 */
module.exports = {
  id: "film",
  name: "手账相册",
  description: "书桌上摊开的相册，一页页贴好",
  preview: ["#F4EEE2", "#211E1B", "#C2381F"],
  degrade: { glassBlur: "0", glassBackground: "rgba(255,253,248,.98)" },
  skin: {
    "--skin-texture": "radial-gradient(rgba(33,30,27,.06) 1px, transparent 1.4px)",
    "--skin-texture-size": "14rpx 14rpx",
    "--skin-title-font": "\"Songti SC\", \"STSong\", \"Noto Serif CJK SC\", \"Source Han Serif SC\", serif",
    "--skin-num-font": "\"Songti SC\", \"STSong\", \"Noto Serif CJK SC\", serif",
    "--skin-mark": "rgba(194,56,31,.28)",
    "--skin-mark-w": "36rpx",
    "--skin-mark-h": "14rpx",
    "--skin-mark-radius": "2rpx",
    "--skin-photo-frame": "10rpx 10rpx 30rpx",
    "--skin-tilt": "-1.2deg",
    "--skin-sticker-tilt": "-6deg",
    "--skin-press": "translateY(2rpx)",
    "--skin-chip-on-bg": "#FFFDF8",
    "--skin-chip-on-text": "#B42318",
    "--skin-chip-on-border": "#C2381F",
    "--skin-sticker-bg": "#FFFDF8",
    "--skin-sticker-text": "#B42318",
    "--skin-clip": "none",
    // 首页模块的主题呈现（2026-10，themes.html 3.3）：转生卡底、按钮投影、胶带、警示色、光晕、头像环、第二贴纸色
    "--skin-hm-bg": "#FFFDF8",
    "--skin-hm-sub": "#6B6258",
    "--skin-btn-shadow": "0 6rpx 0 rgba(33,30,27,.25)",
    "--skin-tape": "rgba(207,227,200,.9)",
    "--skin-tape-alt": "rgba(243,211,198,.9)",
    "--skin-alert": "#C2381F",
    "--skin-glow": "transparent",
    "--skin-avatar-ring": "transparent",
    "--skin-sticker-alt": "#FFFDF8",
    // 冻干充值面板（2026-10-08）：「多送」角标、加送进度条、首充横幅、选中档位
    "--skin-deal": "#C2381F",
    "--skin-deal-2": "#D9573C",
    "--skin-deal-text": "#FFFDF8",
    "--skin-deal-ink": "#B42318",
    "--skin-deal-base": "#D6CAB6",
    "--skin-fc-bg": "#FFFDF8",
    "--skin-fc-text": "#211E1B",
    "--skin-fc-sub": "#6B6258",
    "--skin-fc-ink": "#B42318",
    "--skin-tier-on-bg": "#FFFDF8",
    "--skin-tier-on-border": "#C2381F",
    // 以下覆盖同名常量（圆角 / 阴影），只在本皮肤的页面子树内生效
    "--skin-press-shadow": "none",
    "--skin-btn-clip": "none",
    "--radius-image-thumb": "4rpx",
    "--radius-image-hero": "4rpx",
    "--radius-pill": "12rpx",
    "--radius-sm": "6rpx",
    "--radius-md": "8rpx",
    "--radius-lg": "8rpx",
    "--shadow-card": "0 6rpx 0 rgba(33,30,27,.1)",
    "--shadow-image": "0 6rpx 16rpx rgba(33,30,27,.18)",
    "--shadow-float": "0 10rpx 24rpx rgba(33,30,27,.2)",
    "--shadow-press": "0 2rpx 0 rgba(33,30,27,.12)"
  },
  tokens: {
    primary: "#C2381F",
    secondary: "#3E6B4F",
    background: "#F4EEE2",
    surface: "#EAE2D2",
    cardBackground: "#FFFDF8",
    textPrimary: "#211E1B",
    textSecondary: "#6B6258",
    border: "#DDD3C2",
    divider: "#E6DDCD",

    success: "#3E6B4F",
    warning: "#7A5A00",
    error: "#B42318",
    disabled: "#CFC5B5",
    successSurface: "#E4EDE3",
    errorSurface: "#F8E4DF",

    aiGradientStart: "#211E1B",
    aiGradientEnd: "#3E3833",
    aiGlow: "rgba(194,56,31,.16)",
    aiGradientAngle: "120deg",

    buttonPrimary: "#211E1B",
    buttonSecondary: "#FFFDF8",
    buttonDisabled: "#E6DDCD",
    buttonPrimaryText: "#FFFDF8",
    buttonSecondaryText: "#211E1B",
    buttonRadius: "12rpx",

    cardRadius: "8rpx",
    cardShadow: "0 6rpx 0 rgba(33,30,27,.1)",
    cardBlur: "0",
    cardBorder: "2rpx solid #DDD3C2",
    cardRadiusVariant: "8rpx",
    borderHighlight: "0 solid transparent",

    pagePadding: "32rpx",
    sectionSpacing: "48rpx",
    pageBottomSafe: "190rpx",
    navBarBackground: "#F4EEE2",
    navBarTextStyle: "black",

    titleSize: "44rpx",
    bodySize: "28rpx",
    smallSize: "24rpx",
    eyebrowSize: "20rpx",
    titleWeight: 700,
    titleLetterSpacing: "0",

    transitionDuration: "240ms",
    animationType: "fade",
    transitionEasing: "cubic-bezier(.22,.61,.36,1)",
    glowAnimation: false,

    // 抽屉：相纸白实底，像从相册里抽出的一页
    glassBackground: "rgba(255,253,248,.97)",
    glassBackgroundSolid: "#FFFDF8",
    glassBorder: "2rpx solid rgba(33,30,27,.1)",
    glassBlur: "0",
    glassRadius: "16rpx 16rpx 0 0",
    glassShadow: "0 -8rpx 24rpx rgba(33,30,27,.16)",
    glassScrim: "#211E1B",
    glassScrimMax: 0.30,
    glassTextPrimary: "#211E1B",
    glassTextSecondary: "#6B6258",
    glassHandle: "rgba(33,30,27,.24)"
  }
};
