export const PET_ART_PHOTO_TEMPLATE_ID = "pet-art-photo";
export const PET_ART_PHOTO_VERSION = "v05";

export const petArtPhotoScenes = [
  { id: "window-morning", title: "蓝格睡衣卧室", description: "床上打哈欠 · 慵懒放松", prompt: "A real bright bedroom set with a blue gingham duvet, pale blue pillows and a tall window. The pet wears a soft blue gingham sleep cap and matching pajama collar, sitting in the bedding with a natural wide yawn. Morning window light and tactile cotton." },
  { id: "garden-curious", title: "绿幕恐龙朋友", description: "抱住玩偶 · 天真好奇", prompt: "A real green studio set with a leafy-green backdrop, knitted dinosaur hood and large soft plush dinosaur. The pet wears a simple green dinosaur hoodie and leans against the plush toy, looking toward camera with a curious innocent expression." },
  { id: "studio-confident", title: "薄荷领带影棚", description: "端坐回望 · 自信从容", prompt: "A red-and-cream editorial photo studio with a folding canvas deck chair, low wooden set edge and unbranded glass soda bottles. The pet wears a mint pinstripe shirt and turquoise tie, sitting upright and looking directly into the lens." },
  { id: "night-playful", title: "星夜小王子", description: "披风坐定 · 安静幻想", prompt: "A real dark-blue theatrical studio with paper stars, a small moon prop and a tiny plush fox. The pet wears a knitted mint sweater, mustard scarf and lightweight yellow cape, sitting naturally and gazing slightly upward. Photographic practical lights, no fantasy glow." },
  { id: "seaside-breeze", title: "柠檬黄日记", description: "柠檬入镜 · 俏皮大笑", prompt: "A saturated yellow tabletop studio with two fresh lemons on small stands, a red gingham head scarf and yellow gingham bib. The pet sits centered with a relaxed open-mouth expression. Real fruit and fabric texture, no hands." },
  { id: "library-whisper", title: "复古摄影师", description: "相机在旁 · 慢慢观察", prompt: "A warm cream vintage photography corner with brown corduroy jacket, silk neck scarf, tortoiseshell sunglasses and a compact film camera on the floor. The pet lies with front paws crossed and looks calmly past the lens. Natural window light." },
  { id: "autumn-leaves", title: "蓝调杂志封面", description: "耳机与领带 · 俏皮凝视", prompt: "A deep navy editorial set with orange-and-white over-ear headphones around the pet's neck, pale blue striped shirt and navy diagonal-striped tie. The pet sits in a confident three-quarter pose with a slightly open happy mouth. Blank background, no masthead or text." },
  { id: "snow-cabin", title: "黑白经典肖像", description: "黑白影棚 · 温柔凝视", prompt: "A timeless black-and-white film portrait on a pale gray seamless studio set. The pet sits naturally in a small dark velvet bow tie, looking slightly off-camera with a gentle expression. Real studio spotlight, soft contact shadow, textured floor and subtle silver-gelatin grain." },
  { id: "cafe-afternoon", title: "玫红眼镜写真", description: "衬衫领带 · 轻松回眸", prompt: "A rose-red and blush-pink real seamless-paper studio with soft reflected light. The pet wears a lavender-blue striped shirt, black tie with thin light stripes and oversized dark eyeglasses fitted naturally. Three-quarter standing pose, friendly tongue just visible." },
  { id: "lakeside-sunset", title: "草地花环午后", description: "花束相伴 · 温柔凝视", prompt: "A real outdoor garden portrait on a low picnic blanket with woven flower basket, loose daisies and gingham ribbon. The pet wears a pale linen collar with a tiny flower garland, sitting upright and gazing softly toward camera. Late-afternoon sunlight." },
  { id: "city-rain", title: "街头雨衣", description: "雨后水洼 · 小心探步", prompt: "A real covered city arcade after rain with clear acrylic umbrella, wet stone reflections and a small yellow raincoat on a low hook. The pet wears a mustard rain cape and carefully steps around a shallow puddle, looking down at the reflection. No signs or logos." },
  { id: "spring-picnic", title: "软玩具野餐", description: "野餐垫上 · 伸爪拨带", prompt: "A real spring picnic scene with blue checked blanket, woven basket, fabric ribbons, small plush rabbit and flowering branches. The pet wears a light knitted vest and gently bats one ribbon with one front paw while watching it. Bright daylight, no text." },
  { id: "railway-traveler", title: "复古车站旅人", description: "月台漫步 · 回望列车", samplePet: "golden", prompt: "A real vintage railway platform with teal train carriage, cream luggage trunk and warm ticket-window light. The pet wears a rust-red knit scarf and walks toward camera while looking back at the train; all four paws connect naturally with the platform, with a canvas travel bag beside the bench. Full body and platform architecture visible, no readable signs." },
  { id: "tennis-champion", title: "网球场冠军", description: "追球小跑 · 活力昂扬", samplePet: "golden", prompt: "A sunlit turquoise tennis court with a white net, two loose yellow tennis balls and a wooden racket safely beyond the pet's path. The pet wears a white athletic neckerchief with mint trim and trots diagonally after a loose ball, one forepaw raised mid-step and the others grounded. Dynamic editorial sports photography, no logos or text." },
  { id: "greenhouse-gardener", title: "温室小园丁", description: "低头嗅香 · 好奇探寻", samplePet: "golden", prompt: "A bright glass greenhouse with terracotta pots, hanging ferns, a low watering can and a clear aisle. The pet wears a faded-denim gardening apron, leans its head down to sniff rosemary at muzzle height, with shoulders and all paws visible on the greenhouse floor. Fresh leaf green and warm clay tones, no text." },
  { id: "sailboat-holiday", title: "帆船甲板假日", description: "甲板卧歇 · 迎着海风", samplePet: "golden", prompt: "A real small sailboat moored in calm blue water, with striped canvas sail, rope coils and a low safe deck. The pet wears a cream-and-blue sailor collar and lies securely on the dry deck with front paws crossed and chin raised into the breeze. Clear midday light, visible sailboat context, no logos or text." },
  { id: "berry-pastry-chef", title: "莓果甜品师", description: "甜点车旁 · 认真端详", samplePet: "poodle", prompt: "A cheerful real bakery studio with mint tiled wall, stainless pastry tray, strawberries and one unbranded berry tart on a low pastry cart. The pet wears a cream chef neckerchief and soft fabric cap, stands on the bakery floor beside the cart and looks intently at the tart. Coral and mint accents, realistic food texture, no people, logos or text." },
  { id: "paper-flower-window", title: "纸花橱窗主角", description: "彩纸花间 · 轻快走过", samplePet: "poodle", prompt: "A coral-pink studio shop window filled with handcrafted paper flowers on visible stems, a pale mint low plinth and soft daylight through glass. The pet wears a small cream bow collar and walks between the flowers on the plinth, one forepaw forward and head turned gently toward camera. Crisp paper edges, real fur and clear body-to-plinth contact, no words or logos." },
  { id: "mountain-cable-car", title: "山顶缆车乘客", description: "车厢望远 · 警觉好奇", samplePet: "poodle", prompt: "Inside a stationary mountain cable-car cabin with a large clear window, distant snowy ridges and warm woven seat fabric. The pet wears a padded teal vest and soft mustard scarf, stands safely on the broad upholstered seat with paws pressing into the fabric, and looks out toward the mountains. Cabin frame and believable glass reflections visible, no text." },
  { id: "laundry-day", title: "彩色洗衣日", description: "抽出方巾 · 俏皮一刻", samplePet: "poodle", prompt: "A tidy pastel laundry room with a front-loading machine, colorful folded towels and a low wicker basket of clean cloth. The pet wears a red gingham bandana and gently pulls one small gingham towel from the basket with its mouth while standing on the floor. Real fabric folds and candid domestic photography, no people, logos or text." },
  { id: "museum-curator", title: "琥珀博物馆", description: "展柜旁漫步 · 好奇回头", samplePet: "british", prompt: "A small design museum gallery with amber glass display cases, sculptural ceramics, pale stone floor and soft spotlights. The pet wears a narrow burgundy velvet bow collar and walks slowly beside a low exhibit plinth, one forepaw lifted and head turned toward a ceramic object. Real floor contact, refined amber and cool gray palette, no readable labels or text." },
  { id: "poolside-vacation", title: "蓝色泳池假日", description: "躺椅舒展 · 慵懒晒暖", samplePet: "british", prompt: "A real outdoor poolside terrace with clear blue water, striped parasol and white towels. The pet wears a lemon-yellow linen collar and reclines lengthwise on a low dry deck chair away from the pool edge, front paws stretched toward camera with fur catching midday sunlight. Complete pet visible, no text, people or wet fur." },
  { id: "post-office", title: "旧书邮局来信", description: "轻触包裹 · 好奇查看", samplePet: "british", prompt: "An old-fashioned postal sorting room with wooden pigeonholes, blank cream envelopes, twine-wrapped parcels and a green banker lamp. The pet wears a moss-green waistcoat, stands on a low sorting table and reaches one paw toward the twine of a small parcel while the other paws stay firmly grounded. Curious side profile, warm paper and wood texture, no readable writing or logos." },
  { id: "ballet-backstage", title: "紫色芭蕾后台", description: "走出幕布 · 优雅回眸", samplePet: "british", prompt: "A real theater backstage corner with plum velvet curtain, ballet slippers on a low wooden trunk and warm mirror bulbs. The pet wears a delicate lavender ribbon collar and steps out between the curtains onto the trunk, one forepaw raised, relaxed tail and clear contact with the wood. Lilac and plum theatrical tones, no tutu, human body or text." },
] as const;

export type PetArtPhotoSceneId = typeof petArtPhotoScenes[number]["id"];
export const PET_ART_PHOTO_SCENE_IDS = petArtPhotoScenes.map((scene) => scene.id) as [PetArtPhotoSceneId, ...PetArtPhotoSceneId[]];

export const legacyStyleSceneMap: Record<string, PetArtPhotoSceneId> = {
  "warm-film": "window-morning",
  "paper-cut": "garden-curious",
  studio: "studio-confident",
  fantasy: "night-playful",
};

export function resolvePetArtPhotoScene(input: { scene?: PetArtPhotoSceneId; style?: string }): PetArtPhotoSceneId {
  return input.scene || (input.style && legacyStyleSceneMap[input.style]) || "window-morning";
}

export function buildPetArtPhotoPrompt(sceneId: PetArtPhotoSceneId, rerollReason?: string) {
  const scene = petArtPhotoScenes.find((item) => item.id === sceneId);
  if (!scene) throw new Error("PET_ART_PHOTO_SCENE_INVALID");
  return [
    "Create one premium photorealistic editorial pet photograph using Image 1 as the sole pet identity reference.",
    "Preserve the pet's species, breed, facial structure, eye color, coat color and markings, actual age and healthy proportions. The pet must remain recognizable as the exact same individual. Do not copy the breed or markings of public sample images.",
    `Scene, action, expression, lighting and framing: ${scene.prompt}`,
    "Keep the complete pet visible at about 45-65% of frame height. Make clothing, props and the real set legible while preserving natural contact, fur texture and lens perspective. No human hands, extra limbs, duplicate pets, CGI, illustration, brand marks, pseudo-text, logo or watermark.",
    rerollReason === "pet-not-like" ? "Strengthen identity match to Image 1 while preserving the selected scene, action and expression." : "",
    rerollReason === "composition" ? "Improve framing and anatomy while preserving the selected scene, action and expression." : "",
    "Return exactly 720x1280.",
  ].filter(Boolean).join(" ");
}
