export const PET_ART_PHOTO_TEMPLATE_ID = "pet-art-photo";
export const PET_ART_PHOTO_VERSION = "v13";

export const petArtPhotoScenes = [
  { id: "window-morning", title: "蓝格睡衣卧室", description: "床上打哈欠 · 慵懒放松", prompt: "A real bright bedroom set with a blue gingham duvet, pale blue pillows and a tall window. The pet wears a soft blue gingham sleep cap and matching pajama collar, sitting in the bedding with a natural wide yawn. Morning window light and tactile cotton." },
  { id: "garden-curious", title: "绿幕恐龙朋友", description: "抱住玩偶 · 天真好奇", prompt: "A real green studio set with a leafy-green backdrop, knitted dinosaur hood and large soft plush dinosaur. The pet wears a simple green dinosaur hoodie and leans against the plush toy, looking toward camera with a curious innocent expression." },
  { id: "studio-confident", title: "薄荷领带影棚", description: "端坐回望 · 自信从容", prompt: "A red-and-cream editorial photo studio with a folding canvas deck chair, low wooden set edge and unbranded glass soda bottles. The pet wears a mint pinstripe shirt and turquoise tie, sitting upright and looking directly into the lens." },
  { id: "night-playful", title: "星夜小王子", description: "披风坐定 · 安静幻想", prompt: "A real dark-blue theatrical studio with paper stars, a small moon prop and a tiny plush fox. The pet wears a knitted mint sweater, mustard scarf and lightweight yellow cape, sitting naturally and gazing slightly upward. Photographic practical lights, no fantasy glow." },
  { id: "seaside-breeze", title: "柠檬黄日记", description: "柠檬入镜 · 俏皮大笑", prompt: "A saturated yellow tabletop studio with two fresh lemons on small stands, a red gingham head scarf and yellow gingham bib. The pet sits centered with a relaxed open-mouth expression. Real fruit and fabric texture, no hands." },
  { id: "library-whisper", title: "复古摄影师", description: "相机在旁 · 慢慢观察", prompt: "A warm cream vintage photography corner with brown corduroy jacket, silk neck scarf, tortoiseshell sunglasses and a compact film camera on the floor. The pet lies with front paws crossed and looks calmly past the lens. Natural window light." },
  { id: "autumn-leaves", title: "蓝调杂志封面", description: "耳机与领带 · 俏皮凝视", prompt: "A deep navy editorial set with orange-and-white over-ear headphones around the pet's neck, pale blue striped shirt and navy diagonal-striped tie. The pet sits in a confident three-quarter pose with a slightly open happy mouth. Blank background, no masthead or text." },
  { id: "snow-cabin", title: "黑白经典肖像", description: "黑白影棚 · 温柔凝视", prompt: "A timeless black-and-white film portrait on a pale gray seamless studio set. The pet sits naturally in a small dark velvet bow tie, looking slightly off-camera with a gentle expression. Real studio spotlight, soft contact shadow, textured floor and subtle silver-gelatin grain." },
  { id: "cafe-afternoon", title: "玫红眼镜写真", description: "衬衫领带 · 轻松回眸", prompt: "A rose-red and blush-pink real seamless-paper studio with soft reflected light. The pet wears a lavender-blue striped shirt, black tie with thin light stripes and oversized dark eyeglasses fitted naturally. Three-quarter standing pose, friendly tongue just visible." },
  { id: "lakeside-sunset", title: "草地花环午后", description: "花束相伴 · 温柔凝视", prompt: "A real outdoor garden portrait on a low picnic blanket with woven flower basket, loose daisies and gingham ribbon. The pet wears a pale linen collar with a tiny flower garland, sitting upright and gazing softly toward camera. Late-afternoon sunlight." },
  { id: "city-rain", title: "街头雨衣", description: "雨后水洼 · 小心探步", prompt: "A real covered city arcade after rain with clear acrylic umbrella, wet stone reflections and a small yellow raincoat on a low hook. The pet wears a mustard rain cape and carefully steps around a shallow puddle, looking down at the reflection. No signs or logos." },
  { id: "spring-picnic", title: "软玩具野餐", description: "野餐垫上 · 伸爪拨带", prompt: "A real spring picnic scene with blue checked blanket, woven basket, fabric ribbons, small plush rabbit and flowering branches. The pet wears a light knitted vest and gently bats one ribbon with one front paw while watching it. Bright daylight, no text." },
  { id: "railway-traveler", title: "放大镜大眼", description: "镜片后面 · 一只眼超大", samplePet: "tuxedo", prompt: "A real pet photo studio with a sage-green seamless paper backdrop curving into the floor and one large softbox from the left. A big old brass magnifying glass stands on a small wooden stand right in front of the cat's face, so through the lens one eye and part of the nose look comically huge while the rest of the face stays normal size. The cat sits still and stares curiously into the lens, ears forward. No clothing.", framing: "Close-up at the cat's eye level: the head and the magnifying glass fill about 60-70% of the frame." },
  { id: "tennis-champion", title: "风扇吹毛", description: "小风扇对着吹 · 毛乱飞", samplePet: "cream", prompt: "A real pet photo studio with a butter-yellow seamless paper backdrop curving into the floor and soft even light. A small vintage mint-green desk fan sits on the floor right beside the cat and blows straight at it: the long fluffy fur on its cheeks and chest streams backwards, whiskers swept back, eyes squeezed into happy slits as if enjoying the breeze. No clothing.", framing: "Medium shot: the cat's head and chest fill about 55-70% of the frame, the fan visible at the edge." },
  { id: "greenhouse-gardener", title: "小拳击手", description: "戴上拳套 · 一脸认真", samplePet: "corgi", prompt: "A real pet photo studio with a bright cobalt-blue seamless paper backdrop curving into the floor and crisp soft light. The corgi sits up on its haunches with both front paws raised, each paw inside a small soft red plush boxing glove, mouth closed in a determined, serious look, ears up. A small white towel hangs over one shoulder like a boxer's. Simple, funny and graphic." },
  { id: "sailboat-holiday", title: "礼物盒惊喜", description: "顶开盒盖 · 探出圆脸", samplePet: "british", prompt: "A real pet photo studio with a tomato-red seamless paper backdrop curving into the floor and soft frontal light. A plain white square gift box sits on the floor; the cat has just pushed up the lid with its head, the lid tilted on top of its round face, a loose cream satin ribbon draped over one ear. Only its head and front paws on the box rim are visible, eyes wide and round. No clothing." },
  { id: "berry-pastry-chef", title: "半空接球", description: "腾空一跃 · 张嘴接住", samplePet: "golden", prompt: "A vivid lime-green seamless studio backdrop with crisp high-speed flash. The pet is frozen mid-air in a joyful leap, all four paws off the ground, mouth wide open about to catch a soft red fabric ball right in front of its face, ears flipped up and flying, fur rippling with motion. The pet wears a small sunflower-yellow bandana. Energetic, sharp, perfectly frozen action with a soft shadow on the floor below.", framing: "Full body in mid-air: the pet is about 60-75% of frame height with visible space between its paws and the floor." },
  { id: "paper-flower-window", title: "叼一束花", description: "叼着郁金香 · 来送花", samplePet: "poodle", prompt: "A real pet photo studio with a blush-pink seamless paper backdrop curving into the floor and soft window-like light. The poodle sits neatly and gently holds a small bouquet of three pastel tulips wrapped in brown kraft paper in its mouth, eyes looking up at the camera, a little proud and hopeful. It wears a small cream satin bow tie. Two tulip petals lie on the floor." },
  { id: "mountain-cable-car", title: "大鼻子", description: "凑到镜头前 · 鼻子好大", samplePet: "blacklab", prompt: "A real pet photo studio with a soft lavender seamless paper backdrop curving into the floor and one large softbox. Shot with a wide-angle lens very close to the dog: its wet black nose almost touches the lens and looks big in the foreground, while its eyes behind look up into the camera with curious, slightly raised brows and its ears fall away toward the back. Natural wide-angle perspective, not an extreme fisheye. No clothing.", framing: "Extreme close-up: the dog's head fills the frame, the nose in the lower foreground." },
  { id: "laundry-day", title: "钻进大毛衣", description: "从领口钻出来 · 只露脑袋", samplePet: "shorthair", prompt: "A real pet photo studio with a warm cream seamless paper backdrop curving into the floor and soft side light. An oversized chunky oatmeal cable-knit human sweater lies crumpled on the floor; the cat has crawled inside it and pokes only its head out of the neck opening, one front paw sticking out of a long sleeve cuff, eyes bright and a little mischievous. Soft wool texture." },
  { id: "museum-curator", title: "第一天上学", description: "小黄帽小书包 · 乖乖坐好", samplePet: "calico", prompt: "A real pet photo studio with a pale sky-blue seamless paper backdrop curving into the floor and soft even light. The cat sits upright on a small natural-wood children's chair, wearing a tiny round yellow school hat and a small red backpack, front paws together, looking up at the camera with big curious eyes, a little unsure. Nothing else in the frame." },
  { id: "poolside-vacation", title: "泳圈小将", description: "坐进泳圈 · 不太情愿", samplePet: "persian", prompt: "A real pet photo studio with a aqua-blue seamless paper backdrop curving into the floor and bright soft light. A pastel pink inflatable swim ring lies flat on the floor and the cat sits in the middle of it, a pair of small kids' swim goggles pushed up on its forehead, its flat face wearing a hilariously unimpressed, grumpy expression straight at the camera. No other props." },
  { id: "post-office", title: "追纸飞机", description: "纸飞机飞过 · 抬爪去够", samplePet: "siamese", prompt: "A real pet photo studio with a pale peach seamless paper backdrop curving into the floor and soft light. A white paper airplane glides just above the cat's head, slightly motion-blurred; the cat rears up on its hind legs and reaches one front paw toward it, eyes locked on the plane, mouth slightly open. The cat wears a thin red collar. Captured at the peak of the movement.", framing: "Full body: the cat is about 55-70% of frame height with the paper airplane above it." },
  { id: "ballet-backstage", title: "气球派对", description: "抬头望气球 · 眼睛亮晶晶", samplePet: "greyhound", prompt: "A sunny mustard-yellow painted wall and a pale floor. A bunch of five pastel balloons on ribbons is tied gently to the pet's harness and floats above it. The pet sits and looks straight up at the balloons with wide sparkling eyes and an open happy mouth, one front paw lifting slightly as if hoping to float away. Bright, playful, joyful colour story. Plain balloons with no print.", framing: "The seated pet is about 50-60% of frame height, with the balloons visible above its head." },
  { id: "shorthair-armchair", title: "滑板少年", description: "踩着滑板 · 一路滑过", samplePet: "husky", prompt: "A real pet photo studio with a light grey seamless paper backdrop curving into the floor and a smooth grey floor. The husky stands confidently on a pastel-green skateboard rolling across the studio floor, the wheels slightly motion-blurred, ears back in the wind, mouth open in a happy pant. It wears a small orange bandana. A panned shot with a sense of motion and a sharp face.", framing: "Side view, full body: the dog and skateboard fill about 60-70% of the frame width." },
  { id: "shorthair-books", title: "吹风机造型", description: "长毛被吹起 · 一脸淡定", samplePet: "afghan", prompt: "A real pet photo studio with a soft peach seamless paper backdrop curving into the floor and flattering soft light. A small retro mint-green hair dryer rests on the floor just out of the dog's way and blows a gentle stream of air at it, so the long silky ears and the fur on its head lift and flow sideways in the breeze, while the dog keeps its chin up and gives the camera a calm, elegant side glance, completely unbothered. It wears a thin gold-tone collar. Funny but elegant.", framing: "Medium close-up: head and shoulders fill about 60-70% of the frame, the flowing fur clearly visible." },
  { id: "shorthair-night-rim", title: "黑金礼服", description: "昂首睥睨 · 礼服绅士", samplePet: "sphynx", prompt: "A high-fashion magazine cover portrait against a deep oxblood-red seamless backdrop, with the carved edge of an ornate gilded picture frame visible behind one shoulder. Half-body framing from head to chest. The Sphynx cat sits tall with its chin raised high, looking down its nose at the camera with half-lidded, aloof, regal eyes. The cat wears a tailored black tuxedo jacket with glossy satin lapels over a crisp white shirt collar and a black silk bow tie. One hard beauty-dish key light from high camera left, deep controlled shadows, glossy editorial finish." },
  { id: "shorthair-paper-bag", title: "毛线帽", description: "大绒球毛线帽 · 歪头看你", samplePet: "sphynx", prompt: "A real pet photo studio with a mustard-yellow seamless paper backdrop curving into the floor and soft side light. The Sphynx cat wears a chunky knitted cream beanie with a big fluffy pom-pom, its large ears pushed sideways under the knit, the wrinkly forehead peeking out beneath the brim. It tilts its head to one side and looks into the camera with wide curious eyes.", framing: "Close-up: the head and beanie fill about 60-70% of the frame." },
  { id: "corgi-denim", title: "机车先生", description: "皮衣回眸 · 酷感气场", samplePet: "afghan", prompt: "A bold fashion editorial against a saturated mustard-yellow seamless backdrop. A glossy black motorcycle helmet rests on a chrome bar stool at one side of the frame. Half-body framing from head to chest. The dog stands side-on and turns its head over its shoulder to stare straight into the lens with a cool, unimpressed expression. The dog wears a fitted black leather biker jacket with silver zips and a wide notched collar. Crisp hard key light with a clean shadow on the backdrop, punchy graphic color." },
  { id: "corgi-crate", title: "丝绒王座", description: "端坐高背椅 · 贵族气质", samplePet: "greyhound", prompt: "A luxury fashion editorial set: a tall carved-back armchair upholstered in deep emerald velvet against a smoky dark-taupe painted backdrop. One large soft key light from camera left, rich falloff into shadow. The Italian Greyhound sits upright on the velvet seat with long legs neatly together and chin raised, looking past the camera with aristocratic poise. The dog wears a fitted black-and-gold brocade coat with a high collar. Opulent, refined, dramatic yet tasteful." },
  { id: "corgi-sploot", title: "毛线团缠住", description: "打滚玩毛线 · 越缠越乱", samplePet: "blackcat", prompt: "A real pet photo studio with a light pink seamless paper backdrop curving into the floor and soft overhead light. The black cat lies on its back on the floor, tangled in loose red yarn unspooling from a big ball, hugging the yarn ball with its front paws and kicking it with its hind paws, green eyes wide and playful, mouth slightly open. No clothing." },
  { id: "corgi-sweater", title: "西瓜啃啃", description: "咬一口西瓜 · 眯眼满足", samplePet: "shiba", prompt: "A real pet photo studio with a mint-green seamless paper backdrop curving into the floor and bright soft light. A thick triangle slice of seedless red watermelon lies on the floor; the Shiba bites into the tip of it, eyes squinting with joy, a little juice on its chin. It wears a thin red-and-white striped bandana. Fresh summer colours." },
  { id: "calico-silk", title: "抱着玩偶睡", description: "搂紧玩偶 · 睡到吐舌", samplePet: "golden", prompt: "Soft morning light on a white bed with a rumpled lavender duvet. The pet sleeps on its side hugging a soft plush bear almost as big as its head with both front paws, cheek squished against the plush, the tip of its tongue peeking out. Sleepy, innocent and heart-melting. Pastel lavender and cream palette, no clothing." },
  { id: "calico-bowl", title: "冰淇淋舔舔", description: "伸舌头够 · 专注对眼", samplePet: "corgi", prompt: "A sunny summer set with a pastel turquoise backdrop and the scalloped edge of a pink striped awning at the top. A pet-safe frozen yogurt cone stands in a little wooden holder right in front of the pet. The pet stretches out its tongue to lick the very top, eyes slightly crossed with focus, ears perked. The pet wears a tiny white sailor collar. Fresh, sweet, playful summer moment, no text." },
  { id: "calico-rain-window", title: "害羞捂眼", description: "爪子捂眼睛 · 偷偷看你", samplePet: "greyhound", prompt: "A real pet photo studio with a warm cream seamless paper backdrop curving into the floor and soft light. The dog lies on the floor with its chin down and covers its eyes with one front paw, peeking out from under it with one eye, looking shy and adorable. A small red plush heart cushion lies beside its paws. No clothing.", framing: "Low camera at floor level: the dog's head and paws fill about 55-70% of the frame." },
  { id: "calico-cane-stool", title: "墨镜风衣", description: "立领风衣 · 墨镜压低", samplePet: "siamese", prompt: "A chic fashion magazine portrait against a saturated cobalt-blue seamless backdrop, with the curved back of a white bentwood chair visible beside the cat. Half-body framing from head to chest. The cat sits upright with its head slightly tilted down, gazing over the top of the sunglasses at the camera with a confident, knowing look. The cat clearly wears tortoiseshell sunglasses on its face, resting low on its nose, and a camel trench coat with the collar popped up. Crisp editorial light, clean graphic shadow." },
] as const;

export type PetArtPhotoSceneId = typeof petArtPhotoScenes[number]["id"];
export const PET_ART_PHOTO_SCENE_IDS = petArtPhotoScenes.map((scene) => scene.id) as [PetArtPhotoSceneId, ...PetArtPhotoSceneId[]];

export const legacyStyleSceneMap: Record<string, PetArtPhotoSceneId> = {
  "warm-film": "window-morning",
  "paper-cut": "garden-curious",
  studio: "studio-confident",
  fantasy: "night-playful",
};

export function resolvePetArtPhotoScene(input: { scene?: PetArtPhotoSceneId; style?: string }): PetArtPhotoSceneId {
  return input.scene || (input.style && legacyStyleSceneMap[input.style]) || "window-morning";
}

export function buildPetArtPhotoPrompt(sceneId: PetArtPhotoSceneId, rerollReason?: string) {
  const scene = petArtPhotoScenes.find((item) => item.id === sceneId);
  if (!scene) throw new Error("PET_ART_PHOTO_SCENE_INVALID");
  return [
    "Create one premium photorealistic editorial pet photograph using Image 1 as the sole pet identity reference.",
    "Preserve the pet's species, breed, facial structure, eye color, coat color and markings, actual age and healthy proportions. The pet must remain recognizable as the exact same individual. Do not copy the breed or markings of public sample images.",
    `Scene, action, expression, lighting and framing: ${scene.prompt}`,
    // v12 / v13 的棚拍瞬间场景各自规定取景（特写、俯拍、半张脸）；没给的仍用通用取景，1–12 的提示词逐字不变。
    ("framing" in scene && scene.framing ? `Framing: ${scene.framing}` : "Keep the complete pet visible at about 45-65% of frame height.") + " Keep any props and the real set legible while preserving natural contact, fur texture and lens perspective. No human hands, extra limbs, duplicate pets, CGI, illustration, brand marks, pseudo-text, logo or watermark.",
    rerollReason === "pet-not-like" ? "Strengthen identity match to Image 1 while preserving the selected scene, action and expression." : "",
    rerollReason === "composition" ? "Improve framing and anatomy while preserving the selected scene, action and expression." : "",
    "Return exactly 720x1280.",
  ].filter(Boolean).join(" ");
}
