export const PET_ART_PHOTO_TEMPLATE_ID = "pet-art-photo";
export const PET_ART_PHOTO_VERSION = "v14";

export const petArtPhotoScenes = [
  { id: "window-morning", title: "蓝格睡衣卧室", description: "床上打哈欠 · 慵懒放松", prompt: "A real bright bedroom set with a blue gingham duvet, pale blue pillows and a tall window. The pet wears a soft blue gingham sleep cap and matching pajama collar, sitting in the bedding with a natural wide yawn. Morning window light and tactile cotton." },
  { id: "garden-curious", title: "绿幕恐龙朋友", description: "抱住玩偶 · 天真好奇", prompt: "A real green studio set with a leafy-green backdrop, knitted dinosaur hood and large soft plush dinosaur. The pet wears a simple green dinosaur hoodie and leans against the plush toy, looking toward camera with a curious innocent expression." },
  { id: "studio-confident", title: "薄荷领带影棚", description: "端坐回望 · 自信从容", prompt: "A red-and-cream editorial photo studio with a folding canvas deck chair, low wooden set edge and unbranded glass soda bottles. The pet wears a mint pinstripe shirt and turquoise tie, sitting upright and looking directly into the lens." },
  { id: "night-playful", title: "星夜小王子", description: "披风坐定 · 安静幻想", prompt: "A real dark-blue theatrical studio with paper stars, a small moon prop and a tiny plush fox. The pet wears a knitted mint sweater, mustard scarf and lightweight yellow cape, sitting naturally and gazing slightly upward. Photographic practical lights, no fantasy glow." },
  { id: "seaside-breeze", title: "柠檬黄日记", description: "柠檬入镜 · 俏皮大笑", prompt: "A saturated yellow tabletop studio with two fresh lemons on small stands, a red gingham head scarf and yellow gingham bib. The pet sits centered with a relaxed open-mouth expression. Real fruit and fabric texture, no hands." },
  { id: "library-whisper", title: "复古摄影师", description: "相机在旁 · 慢慢观察", prompt: "A warm cream vintage photography corner with brown corduroy jacket, silk neck scarf, tortoiseshell sunglasses and a compact film camera on the floor. The pet lies with front paws crossed and looks calmly past the lens. Natural window light." },
  { id: "autumn-leaves", title: "蓝调杂志封面", description: "耳机与领带 · 俏皮凝视", prompt: "A deep navy editorial set with orange-and-white over-ear headphones around the pet's neck, pale blue striped shirt and navy diagonal-striped tie. The pet sits in a confident three-quarter pose with a slightly open happy mouth. Blank background, no masthead or text." },
  { id: "snow-cabin", title: "黑白大片", description: "高领毛衣 · 冷峻凝视", samplePet: "poodle", prompt: "A black-and-white fashion magazine portrait in deep silver-gelatin tones on a charcoal seamless backdrop, a black bentwood cafe chair beside the dog. The poodle sits upright on the floor in a natural dog pose, chin lifted, eyes turned to the camera with a cool, composed look. It wears a real fitted black ribbed-knit dog turtleneck sweater made for dogs: the roll neck sits snugly around its neck, its front legs come through short knitted sleeves and the knit hugs its back and chest, with one slim silver chain collar over the roll neck. One hard side key light, crisp contrast, fine film grain.", framing: "Three-quarter to full body: the pet sits or stands in its own natural animal posture at about 55-70% of frame height, so the pet-cut garment is clearly worn on an animal's body, with the set piece partly visible beside it." },
  { id: "cafe-afternoon", title: "玫红眼镜写真", description: "衬衫领带 · 轻松回眸", prompt: "A rose-red and blush-pink real seamless-paper studio with soft reflected light. The pet wears a lavender-blue striped shirt, black tie with thin light stripes and oversized dark eyeglasses fitted naturally. Three-quarter standing pose, friendly tongue just visible." },
  { id: "lakeside-sunset", title: "花篮小熊", description: "坐进花篮 · 歪头卖萌", samplePet: "teddy", prompt: "A real pet photo studio with a butter-cream seamless paper backdrop curving into the floor and soft window-like key light. A wide low woven wicker basket filled with pastel pink ranunculus and cream peonies sits on the floor; the teddy-cut poodle sits inside the basket among the flowers, round fluffy face tilted to one side, tongue tip just peeking out, eyes bright and sweet. A loose blush satin ribbon trails from the basket handle onto the floor. No clothing.", framing: "Medium shot: the dog and basket fill about 55-70% of the frame." },
  { id: "city-rain", title: "驼色大衣", description: "羊毛外套 · 侧身回望", samplePet: "golden", prompt: "A warm luxury fashion editorial on a soft cream seamless backdrop, a vintage brass coat stand with a brown felt hat on one hook standing beside the dog. The golden retriever stands side-on on all four legs and turns its head back toward the camera with a calm, confident, noble expression, mouth closed. It wears a real tailored camel wool dog coat made for dogs: it covers the back and chest with a small notched collar at the neck, fastens with leather buttons along the chest and a strap under the belly, and the coat follows the curve of its back while its tail and legs stay free. One large soft key light from camera left, rich warm tones.", framing: "Three-quarter to full body: the pet sits or stands in its own natural animal posture at about 55-70% of frame height, so the pet-cut garment is clearly worn on an animal's body, with the set piece partly visible beside it." },
  { id: "spring-picnic", title: "冠军领奖台", description: "站上第一名 · 骄傲挺胸", samplePet: "merle", prompt: "A real pet photo studio with a soft sky-blue seamless paper backdrop curving into the floor and crisp soft light. A small three-step plain white wooden winner's podium with no text or numbers stands on the floor; the Border Collie stands proudly on the top step, chest out, chin up, mouth open in a bright happy pant, one front paw on the edge. A big red satin rosette ribbon is fastened to its collar, and a red flying disc leans against the lower step. Proud, joyful and a little funny.", framing: "Full body: the dog on the podium is about 60-70% of frame height." },
  { id: "railway-traveler", title: "放大镜大眼", description: "镜片后面 · 一只眼超大", samplePet: "tuxedo", prompt: "A real pet photo studio with a sage-green seamless paper backdrop curving into the floor and one large softbox from the left. A big old brass magnifying glass stands on a small wooden stand right in front of the cat's face, so through the lens one eye and part of the nose look comically huge while the rest of the face stays normal size. The cat sits still and stares curiously into the lens, ears forward. A small stack of two old cloth-bound books sits under the stand and an open antique brass pocket watch lies on the floor beside it, like a little explorer's desk. No clothing.", framing: "Close-up at the cat's eye level: the head and the magnifying glass fill about 60-70% of the frame." },
  { id: "tennis-champion", title: "风扇吹毛", description: "小风扇对着吹 · 毛乱飞", samplePet: "cream", prompt: "A real pet photo studio with a butter-yellow seamless paper backdrop curving into the floor and soft even light. A small vintage mint-green desk fan sits on the floor right beside the cat and blows straight at it: the long fluffy fur on its cheeks and chest streams backwards, whiskers swept back, eyes squeezed into happy slits as if enjoying the breeze. Two pale ribbon streamers tied to the fan grille flutter in the wind, and a tall glass of iced lemonade with a lemon slice and a striped paper straw stands on the floor. No clothing.", framing: "Medium shot: the cat's head and chest fill about 55-70% of the frame, the fan visible at the edge." },
  { id: "greenhouse-gardener", title: "格纹小绅士", description: "格纹呢外套 · 乖巧端坐", samplePet: "schnauzer", prompt: "A warm menswear-inspired fashion editorial on a deep forest-green painted backdrop, the arm of a worn cognac leather club chair and a small stack of two hardcover books beside the dog. The Miniature Schnauzer puppy sits upright on the floor in a natural dog pose, head tilted very slightly, big round dark eyes looking sweetly and proudly into the camera, mouth closed, fluffy eyebrows and muzzle softly groomed: polite, adorable and a little dignified. It wears a real red-and-green tartan wool dog coat made for small dogs: it covers its back and chest, its front legs come through the openings, it fastens with a strap under the chest and has a small brown corduroy collar at the neck. One large soft key light from camera left, rich warm tones.", framing: "Three-quarter to full body: the pet sits or stands in its own natural animal posture at about 55-70% of frame height, so the pet-cut garment is clearly worn on an animal's body, with the set piece partly visible beside it." },
  { id: "sailboat-holiday", title: "礼物盒惊喜", description: "顶开盒盖 · 探出圆脸", samplePet: "british", prompt: "A real pet photo studio with a tomato-red seamless paper backdrop curving into the floor and soft frontal light. A plain white square gift box sits on the floor; the cat has just pushed up the lid with its head, the lid tilted on top of its round face, a loose cream satin ribbon draped over one ear. Only its head and front paws on the box rim are visible, eyes wide and round. Two smaller gift boxes in cream and blush paper with satin bows are stacked beside the main box, and a few curls of ribbon lie on the floor. No clothing." },
  { id: "berry-pastry-chef", title: "半空接球", description: "腾空一跃 · 张嘴接住", samplePet: "golden", prompt: "A vivid lime-green seamless studio backdrop with crisp high-speed flash. The pet is frozen mid-air in a joyful leap, all four paws off the ground, mouth wide open about to catch a soft red fabric ball right in front of its face, ears flipped up and flying, fur rippling with motion. The pet wears a small sunflower-yellow bandana. Two more soft fabric balls in mustard and sky blue rest on the floor and a low red-and-white striped training hurdle stands behind. Energetic, sharp, perfectly frozen action with a soft shadow on the floor below.", framing: "Full body in mid-air: the pet is about 60-75% of frame height with visible space between its paws and the floor." },
  { id: "paper-flower-window", title: "千鸟格马甲", description: "毛呢马甲 · 正襟危坐", samplePet: "husky", prompt: "A sharp menswear-inspired fashion editorial on a slate-blue seamless backdrop, two stacked vintage tan leather suitcases beside the dog. The husky sits tall on the floor in a natural dog pose, chest out, gazing straight into the lens with calm, self-assured ice-blue eyes, mouth closed. It wears a real tailored black-and-white houndstooth wool dog vest made for dogs: it covers its back and chest, its front legs pass through the armholes, it fastens with a buckle strap under the chest and has a brown leather trim at the neck, with a matching brown leather collar. Crisp directional key light, clean graphic shadow.", framing: "Three-quarter to full body: the pet sits or stands in its own natural animal posture at about 55-70% of frame height, so the pet-cut garment is clearly worn on an animal's body, with the set piece partly visible beside it." },
  { id: "mountain-cable-car", title: "大鼻子", description: "凑到镜头前 · 鼻子好大", samplePet: "blacklab", prompt: "A real pet photo studio with a soft lavender seamless paper backdrop curving into the floor and one large softbox. Shot with a wide-angle lens very close to the dog: its wet black nose almost touches the lens and looks big in the foreground, while its eyes behind look up into the camera with curious, slightly raised brows and its ears fall away toward the back. A small glass jar of bone-shaped biscuits stands in a lower corner with two biscuits on the floor, as if the dog is sniffing for treats. Natural wide-angle perspective, not an extreme fisheye. No clothing.", framing: "Extreme close-up: the dog's head fills the frame, the nose in the lower foreground." },
  { id: "laundry-day", title: "钻进大毛衣", description: "从领口钻出来 · 只露脑袋", samplePet: "shorthair", prompt: "A real pet photo studio with a warm cream seamless paper backdrop curving into the floor and soft side light. An oversized chunky oatmeal cable-knit human sweater lies crumpled on the floor; the cat has crawled inside it and pokes only its head out of the neck opening, one front paw sticking out of a long sleeve cuff, eyes bright and a little mischievous. A ball of matching oatmeal yarn with two wooden knitting needles and a mug in a knitted cosy sit beside the sweater. Soft wool texture." },
  { id: "museum-curator", title: "第一天上学", description: "小黄帽小书包 · 乖乖坐好", samplePet: "calico", prompt: "A real pet photo studio with a pale sky-blue seamless paper backdrop curving into the floor and soft even light. The cat sits upright on a small natural-wood children's chair, wearing a tiny round yellow school hat and a small red backpack, front paws together, looking up at the camera with big curious eyes, a little unsure. A small stack of colourful picture books with a red apple on top sits on the floor beside the chair, and a small blank wooden-framed chalk slate leans against a chair leg." },
  { id: "poolside-vacation", title: "泳圈小将", description: "戴上泳镜 · 准备下水", samplePet: "schnauzer", prompt: "A real pet photo studio with a aqua-blue seamless paper backdrop curving into the floor and bright soft light. A pastel pink inflatable swim ring lies flat on the floor and the Miniature Schnauzer puppy sits in the middle of it, a pair of small kids' swim goggles pushed up on its fluffy forehead, mouth open in a big happy grin with its tongue showing, ears flopping, bright round eyes looking straight at the camera as if ready to jump in. A small yellow rubber duck sits on the rim of the ring and a folded blue-and-white striped beach towel lies on the floor beside it." },
  { id: "post-office", title: "追纸飞机", description: "纸飞机飞过 · 抬爪去够", samplePet: "siamese", prompt: "A real pet photo studio with a pale peach seamless paper backdrop curving into the floor and soft light. A white paper airplane glides just above the cat's head, slightly motion-blurred; the cat rears up on its hind legs and reaches one front paw toward it, eyes locked on the plane, mouth slightly open. Two more folded paper airplanes have already landed on the floor and a small stack of pastel origami paper lies nearby. The cat wears a thin red collar. Captured at the peak of the movement.", framing: "Full body: the cat is about 55-70% of frame height with the paper airplane above it." },
  { id: "ballet-backstage", title: "气球派对", description: "抬头望气球 · 眼睛亮晶晶", samplePet: "greyhound", prompt: "A sunny mustard-yellow painted wall and a pale floor. A bunch of five pastel balloons on ribbons is tied gently to the pet's harness and floats above it. The pet sits and looks straight up at the balloons with wide sparkling eyes and an open happy mouth, one front paw lifting slightly as if hoping to float away. Bright, playful, joyful colour story. Plain balloons with no print.", framing: "The seated pet is about 50-60% of frame height, with the balloons visible above its head." },
  { id: "shorthair-armchair", title: "滑板少年", description: "踩着滑板 · 一路滑过", samplePet: "whiteschnauzer", prompt: "A real pet photo studio with a light grey seamless paper backdrop curving into the floor and a smooth grey floor. The white Miniature Schnauzer stands confidently on a pastel-green skateboard rolling across the studio floor, the wheels slightly motion-blurred, ears flipped back and white beard blowing in the wind, mouth open in a happy pant. It wears a small orange bandana. A panned shot with a sense of motion and a sharp face.", framing: "Side view, full body: the dog and skateboard fill about 60-70% of the frame width." },
  { id: "shorthair-books", title: "吹风机造型", description: "长毛被吹起 · 一脸淡定", samplePet: "afghan", prompt: "A real pet photo studio with a soft peach seamless paper backdrop curving into the floor and flattering soft light. A small retro mint-green hair dryer rests on the floor just out of the dog's way and blows a gentle stream of air at it, so the long silky ears and the fur on its head lift and flow sideways in the breeze, while the dog keeps its chin up and gives the camera a calm, elegant side glance, completely unbothered. It wears a thin gold-tone collar. Funny but elegant.", framing: "Medium close-up: head and shoulders fill about 60-70% of the frame, the flowing fur clearly visible." },
  { id: "shorthair-night-rim", title: "黑金礼服", description: "昂首睥睨 · 礼服绅士", samplePet: "sphynx", prompt: "A high-fashion magazine cover portrait against a deep oxblood-red seamless backdrop, with the carved edge of an ornate gilded picture frame visible behind one shoulder. Half-body framing from head to chest. The Sphynx cat sits tall with its chin raised high, looking down its nose at the camera with half-lidded, aloof, regal eyes. The cat wears a tailored black tuxedo jacket with glossy satin lapels over a crisp white shirt collar and a black silk bow tie. One hard beauty-dish key light from high camera left, deep controlled shadows, glossy editorial finish." },
  { id: "shorthair-paper-bag", title: "毛线帽", description: "大绒球毛线帽 · 咧嘴一笑", samplePet: "samoyed", prompt: "A real pet photo studio with a mustard-yellow seamless paper backdrop curving into the floor and soft side light. The Samoyed wears a chunky knitted cranberry-red beanie with a big fluffy cream pom-pom, its upright ears poking out through two knitted ear holes, thick white fluff spilling out beneath the brim, black lips curled into its classic Samoyed smile. It tilts its head to one side and looks into the camera with wide curious eyes. A pair of matching cranberry knitted mittens and a mug of hot cocoa topped with marshmallows sit on the floor beside it, a cosy winter set.", framing: "Close-up: the head and beanie fill about 60-70% of the frame." },
  { id: "corgi-denim", title: "机车先生", description: "皮衣回眸 · 酷感气场", samplePet: "afghan", prompt: "A bold fashion editorial against a saturated mustard-yellow seamless backdrop. A glossy black motorcycle helmet rests on a chrome bar stool at one side of the frame. Half-body framing from head to chest. The dog stands side-on and turns its head over its shoulder to stare straight into the lens with a cool, unimpressed expression. The dog wears a fitted black leather biker jacket with silver zips and a wide notched collar. Crisp hard key light with a clean shadow on the backdrop, punchy graphic color." },
  { id: "corgi-crate", title: "丝绒王座", description: "端坐高背椅 · 贵族气质", samplePet: "greyhound", prompt: "A luxury fashion editorial set: a tall carved-back armchair upholstered in deep emerald velvet against a smoky dark-taupe painted backdrop. One large soft key light from camera left, rich falloff into shadow. The Italian Greyhound sits upright on the velvet seat with long legs neatly together and chin raised, looking past the camera with aristocratic poise. The dog wears a fitted black-and-gold brocade coat with a high collar. Opulent, refined, dramatic yet tasteful." },
  { id: "corgi-sploot", title: "毛线团缠住", description: "打滚玩毛线 · 越缠越乱", samplePet: "blackcat", prompt: "A real pet photo studio with a light pink seamless paper backdrop curving into the floor and soft overhead light. The black cat lies on its back on the floor, tangled in loose red yarn unspooling from a big ball, hugging the yarn ball with its front paws and kicking it with its hind paws, green eyes wide and playful, mouth slightly open. A tipped-over wicker knitting basket spills two more yarn balls in cream and mustard onto the floor. No clothing." },
  { id: "corgi-sweater", title: "西瓜啃啃", description: "咬一口西瓜 · 眯眼满足", samplePet: "shiba", prompt: "A real pet photo studio with a mint-green seamless paper backdrop curving into the floor and bright soft light. A thick triangle slice of seedless red watermelon lies on the floor; the Shiba bites into the tip of it, eyes squinting with joy, a little juice on its chin. It wears a thin red-and-white striped bandana. A halved watermelon sits behind it and a woven straw sun hat lies on the floor nearby. Fresh summer colours." },
  { id: "calico-silk", title: "抱着玩偶睡", description: "搂紧玩偶 · 睡到吐舌", samplePet: "golden", prompt: "Soft morning light on a white bed with a rumpled lavender duvet. The pet sleeps on its side hugging a soft plush bear almost as big as its head with both front paws, cheek squished against the plush, the tip of its tongue peeking out. Sleepy, innocent and heart-melting. Pastel lavender and cream palette, no clothing." },
  { id: "calico-bowl", title: "冰淇淋舔舔", description: "伸舌头够 · 专注对眼", samplePet: "corgi", prompt: "A sunny summer set with a pastel turquoise backdrop and the scalloped edge of a pink striped awning at the top. A pet-safe frozen yogurt cone stands in a little wooden holder right in front of the pet. The pet stretches out its tongue to lick the very top, eyes slightly crossed with focus, ears perked. The pet wears a tiny white sailor collar. Fresh, sweet, playful summer moment, no text." },
  { id: "calico-rain-window", title: "害羞捂眼", description: "爪子捂眼睛 · 偷偷看你", samplePet: "greyhound", prompt: "A real pet photo studio with a warm cream seamless paper backdrop curving into the floor and soft light. The dog lies on the floor with its chin down and covers its eyes with one front paw, peeking out from under it with one eye, looking shy and adorable. A small red plush heart cushion lies beside its paws, with a sealed cream envelope closed by a red heart sticker and a few loose red rose petals scattered nearby. No clothing.", framing: "Low camera at floor level: the dog's head and paws fill about 55-70% of the frame." },
  { id: "calico-cane-stool", title: "墨镜风衣", description: "立领风衣 · 墨镜压低", samplePet: "siamese", prompt: "A chic fashion magazine portrait against a saturated cobalt-blue seamless backdrop, with the curved back of a white bentwood chair visible beside the cat. Half-body framing from head to chest. The cat sits upright with its head slightly tilted down, gazing over the top of the sunglasses at the camera with a confident, knowing look. The cat clearly wears tortoiseshell sunglasses on its face, resting low on its nose, and a camel trench coat with the collar popped up. Crisp editorial light, clean graphic shadow." },
] as const;

export type PetArtPhotoSceneId = typeof petArtPhotoScenes[number]["id"];
export const PET_ART_PHOTO_SCENE_IDS = petArtPhotoScenes.map((scene) => scene.id) as [PetArtPhotoSceneId, ...PetArtPhotoSceneId[]];

export const legacyStyleSceneMap: Record<string, PetArtPhotoSceneId> = {
  "warm-film": "window-morning",
  "paper-cut": "garden-curious",
  studio: "studio-confident",
  fantasy: "night-playful",
};

export function resolvePetArtPhotoScene(input: { scene?: PetArtPhotoSceneId; style?: string }): PetArtPhotoSceneId {
  return input.scene || (input.style && legacyStyleSceneMap[input.style]) || "window-morning";
}

export function buildPetArtPhotoPrompt(sceneId: PetArtPhotoSceneId, rerollReason?: string) {
  const scene = petArtPhotoScenes.find((item) => item.id === sceneId);
  if (!scene) throw new Error("PET_ART_PHOTO_SCENE_INVALID");
  return [
    "Create one premium photorealistic editorial pet photograph using Image 1 as the sole pet identity reference.",
    "Preserve the pet's species, breed, facial structure, eye color, coat color and markings, actual age and healthy proportions. The pet must remain recognizable as the exact same individual. Do not copy the breed or markings of public sample images.",
    `Scene, action, expression, lighting and framing: ${scene.prompt}`,
    // v12–v14 的棚拍瞬间与时尚大片各自规定取景（特写、俯拍、半身）；没给的仍用通用取景，1–12 里未替换的 8 套提示词逐字不变。
    ("framing" in scene && scene.framing ? `Framing: ${scene.framing}` : "Keep the complete pet visible at about 45-65% of frame height.") + " Keep any props and the real set legible while preserving natural contact, fur texture and lens perspective. No human hands, extra limbs, duplicate pets, CGI, illustration, brand marks, pseudo-text, logo or watermark.",
    rerollReason === "pet-not-like" ? "Strengthen identity match to Image 1 while preserving the selected scene, action and expression." : "",
    rerollReason === "composition" ? "Improve framing and anatomy while preserving the selected scene, action and expression." : "",
    "Return exactly 720x1280.",
  ].filter(Boolean).join(" ");
}
